<?php
include("db.php"); //INCLUDED DB.PHP HERE SO ON EVERY PAGE YOU INCLUDE AUTH.PHP, DB.PHP WILL AUTOMATICALLY INCLUDED.
if(!isset($_SESSION['EMAIL'])){
    //CHECKING IS SESSION IS "NOT" SET. IF NOT THEN REDIRECT USER TO LOGON PAGE.
    header('Location: logon.php');
    exit(); //TO HALT FURTHER RENDERING AS SOMETIMES BROWSERS FUCK UP(0.01 PROBABILTY) AND MAY THROW AN WARNING INSTEAD OF REDIRECTING.
}
